version: '3.1'

services:
  otusdb:
    image: mysql:8.0.15
    container_name: otusdb
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=otus
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_user_pass
    command: 
      --init-file /init.sql
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
      - /home/astrviktor/otus-databases/hw12/CSVs:/home/root
    expose:
      - "3306"
    ports:
      - "3309:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - otusdb
    environment:
      PMA_HOST: otusdb
      PMA_PORT: 3309
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    ports:
      - 8081:80

volumes:
  data:
